### ISSUE TITLE
Can we make sure that all PR's go through me? 

### ISSUE THREAD

**Issue by TheCurryMan** [VikingHacks/vikinghacks.github.io#11]

**Comment by vikranth22446** [comment]
Why? 
Don't we have write access?

**Comment by leegabriel** [comment]
I think it would be more efficient if Avinash had the final word on the PRs that go through this particular repository (it's one of his main duties). Anyone can submit a pull request, though, including me.

Similarly, I think that the members of the Development Team repositories should have the final word on the PRs for their own repositories.

**Comment by leegabriel** [comment]
Also, Vikranth - could you supply your contact information in the Google Drive? Thanks :)

**Comment by vikranth22446** [comment]
where do we put our information?

**Comment by leegabriel** [comment]
If you go to the Google Drive you will find a spreadsheet called "Development Team Contact Information".  :)

**Comment by LordDarkula** [comment]
*cough Vikranth *cough

**Comment by vikranth22446** [comment]
what are you coughing about?

**Comment by leegabriel** [comment]
Lol you guys xD
